name: Build and Release LaTeX document

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_release_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          continue_on_error: true
          
      - name: Stash PDF
        run: |
          mv main.pdf $HOME # cache the file
          
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: gh_actions_builds
          
      - name: Checkout gh_actions_builds Branch
        uses: actions/checkout@v1
        with:
          ref: gh_actions_builds 
          
      - name: Commit PDF
        run: |
          git config --local user.email "guotao.he.0000@outlook.com"
          git config --local user.name "Guotao He"
          git config --global --add safe.directory /github/workspace
          mv $HOME/main.pdf $(pwd) # bring it back 
          git add -f main.pdf
          git commit -m "Updated by GitHub Action Automatically"
          
      - name: Push PDF
        uses: ad-m/github-push-action@v0.5.0
        with: 
          branch: gh_actions_builds 
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
